image: golang:1.19.5

stages:
  - prepare
  - test   # use in KGM template
  - notice # use in KGM template
  - deploy

include:
  - project: 'ae/kgm'
    file: '/.gitlab/ci/kgm_template.yml'

variables:
  # gotestで利用するmysqlのrootユーザー作成用の変数
  MYSQL_ROOT_PASSWORD: password

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - export PATH="$CI_PROJECT_DIR/.go/bin:$PATH"
  cache:
    - key:
        files:
          - go.sum
        prefix: gomod
      paths:
        - .go/pkg/mod/
      policy: pull-push

gomod:
  stage: prepare
  tags:
    - gorun
  extends: .go-cache
  script:
    - go mod vendor

golangcilint:
  stage: test
  tags:
    - gorun
  image: golangci/golangci-lint:v1.50.1
  extends: .go-cache
  script:
    - make wire
    - make lint

# ※kgm templateがgotestに依存するのでジョブ名は変更しないでください
gotest:
  stage: test
  services:
    - name: mysql:8.0.30
      alias: mysql
  tags:
    - gorun
  extends: .go-cache
  script:
    - make wire
    - make gotest_cover
  variables:
    TOKEN_ENCRYPT_KEY: c5DgPGOlETw7pLxYWrlRErwAF6FZutC1
    TOKEN_SIGNING_KEY: HQcyvtSkoO1v3pyaM2ZvtLvbAWN8eeSd
    # DB接続
    DB_READ_HOST_NAME: mysql
    DB_WRITE_HOST_NAME: mysql
    DB_USER_NAME: root
    DB_PASSWORD: password
    DB_PORT: 3306
    # テストで使用するマイグレーションファイルのパス
    MIGRATE_DIR: /builds/ae/sardine/build/migrate
  artifacts:
    paths:
      - coverage
    expire_in: 1 mos

pages:
   stage: deploy
   tags:
     - gorun
   script:
     - rm -rf public/$CI_COMMIT_REF_NAME
     - mkdir -p public/$CI_COMMIT_REF_NAME
     - mv ./docs/oas/swagger.yml public/$CI_COMMIT_REF_NAME/oas/swagger.yml
     - mv ./docs/oas/index.html public/$CI_COMMIT_REF_NAME/oas/index.html
   artifacts:
     paths:
       - public
   rules:
     - changes:
         - "docs/oas/**/*"
