version: '3.1'

services:
  go:
    build:
      context: ./build/go
      args:
        GO_VERSION: 1.19.5
        LINTER_VERSION: v1.50.1
    container_name: sardine_go
    tty: true
    ports:
      - "28080:8080"
    volumes:
      - ./:/app:cached
    working_dir: /app
    env_file:
      - .env
    command: air -c .air.toml

  mysql:
    build: ./build/mysql
    container_name: sardine_mysql
    ports:
      - "23306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./build/mysql/my.cnf:/etc/my.cnf
      - ./build/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redoc:
    image: redocly/redoc
    ports:
      - 28081:80
    volumes:
      - ./docs/oas/swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      SPEC_URL: swagger.yml

  # ローカルでS3のモックするためのコンテナ
  # @see https://docs.min.io/docs/minio-docker-quickstart-guide.html
  minio:
    container_name: sardine_minio
    image: minio/minio
    ports:
      - "29000:9000" # CLI用のポート
      - "29001:9001" # GUI用のポート
    volumes:
      - ./.minio:/data
    command: server /data --console-address ":9001"

  # 初回起動時にバケットを作るためのコンテナ
  # @see https://github.com/minio/minio/issues/4882#issuecomment-326425896
  mc:
    container_name: sardine_mc
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb -p myminio/local-lms-storage;
      exit 0;
      "

volumes:
  mysql_data: null

