#[[plugins]]
#repo = 'fatih/vim-go'
#on_ft = 'go'
#hook_add = '''
#  let g:go_metalinter_autosave = 1
#  let g:go_metalinter_autosave_enabled = ["vet"]
#  let g:go_highlight_functions = 1
#  let g:go_highlight_methods = 1
#  let g:go_highlight_structs = 1
#  let g:go_def_mapping_enabled = 0
#  let g:go_doc_keywordprg_enabled = 0
#'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_add = '''
  let g:terraform_fmt_on_save = 1
'''

[[plugins]] # TOMLのシンタックスハイライト
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

