[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'GutenYe/json5.vim'
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'md', 'rmd'],
hook_post_update = '''
cd app & yarn install
'''
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')
autocmd FileType go nmap gtj :CocCommand go.tags.add json<cr>
autocmd FileType go nmap gty :CocCommand go.tags.add yaml<cr>
autocmd FileType go nmap gtx :CocCommand go.tags.clear<cr>
function! s:GoToDefinition()
  if CocAction('jumpDefinition')
    return v:true
  endif

  let ret = execute("silent! normal \<C-]>")
  if ret =~ "Error" || ret =~ "错误"
    call searchdecl(expand('<cword>'))
  endif
endfunction
nmap <silent> <Tab>[ <Plug>(coc-definition)
nmap <silent> T <Plug>(coc-type-definition)
nmap <silent> I <Plug>(coc-implementation)
nmap <silent> R <Plug>(coc-references)
nmap <silent> <Tab>] :split \| :call <SID>GoToDefinition()<CR>
'''


#[[plugins]]
#repo = "tbodt/deoplete-tabnine"
#build = "./install.sh"
#on_fmt = ["*"]

#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'
#depends = ['async.vim']
#hook_add = '''
#
#" Go用LSP
#if executable('gopls')
#  augroup LspGo
#    au!
#    au User lsp_setup call lsp#register_server({
#        \ 'name': 'gopls',
#        \ 'cmd': {server_info->['gopls']},
#        \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'go.mod'))},
#        \ 'whitelist': ['go'],
#        \ })
#    autocmd BufWritePre *.go LspDocumentFormatSync
#  augroup END
#endif
#
#" Python用LSP
#if (executable('pyls'))
#    " pylsの起動定義
#    augroup LspPython
#        autocmd!
#        autocmd User lsp_setup call lsp#register_server({
#            \ 'name': 'pyls',
#            \ 'cmd': { server_info -> ['pyls'] },
#            \ 'whitelist': ['python'],
#            \})
#    augroup END
#endif
#
#" Typescript用LSP
#if executable('typescript-language-server')
#    augroup LspTypeScript
#        au!
#        autocmd User lsp_setup call lsp#register_server({
#                    \ 'name': 'typescript-language-server',
#                    \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
#                    \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tsconfig.json'))},
#                    \ 'whitelist': ['typescript', 'typescript.tsx'],
#                    \ })
#        autocmd FileType typescript setlocal omnifunc=lsp#complete
#    augroup END :echomsg "vim-lsp with `typescript-language-server` enabled"
#else
#    :echomsg "vim-lsp for typescript unavailable"
#endif
#
#" SQL
#if executable('sql-language-server')
#    augroup LspSQL
#      au!
#      autocmd User lsp_setup call lsp#register_server({
#          \ 'name': 'sql-language-server',
#          \ 'cmd': {server_info->[&shell, &shellcmdflag, 'sql-language-server up --method stdio']},
#          \ 'whitelist': ['sql'],
#          \ })
#    augroup END
#endif
#
#" Ruby用LSP
#if executable('solargraph')
#    " gem install solargraph
#    au User lsp_setup call lsp#register_server({
#        \ 'name': 'solargraph',
#        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
#        \ 'initialization_options': {"diagnostics": "true"},
#        \ 'whitelist': ['ruby'],
#        \ })
#endif
#
#" PHP用のLSP
#if executable('intelephense')
#  augroup LspPHPIntelephense
#  au!
#  au User lsp_setup call lsp#register_server({
#      \ 'name': 'intelephense',
#      \ 'cmd': {server_info->[&shell, &shellcmdflag, 'intelephense --stdio']},
#      \ 'whitelist': ['php'],
#      \ 'initialization_options': {'storagePath': '/tmp/intelephense'},
#      \ 'workspace_config': {
#      \   'intelephense': {
#      \     'files': {
#      \       'maxSize': 1000000,
#      \       'associations': ['*.php', '*.phtml'],
#      \       'exclude': [],
#      \     },
#      \     'completion': {
#      \       'insertUseDeclaration': v:true,
#      \       'fullyQualifyGlobalConstantsAndFunctions': v:false,
#      \       'triggerParameterHints': v:true,
#      \       'maxItems': 100,
#      \     },
#      \     'format': {
#      \       'enable': v:true
#      \     },
#      \   },
#      \ }
#      \})
#  augroup END
#endif
#
#if executable('terraform-lsp')
#  augroup LspTerraform
#    au!
#    au User lsp_setup call lsp#register_server({
#      \ 'name': 'terraform-lsp',
#      \ 'cmd': {server_info->['terraform-lsp']},
#      \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), '.terraform'))},
#      \ 'whitelist': ['terraform','tf'],
#      \ })
#  augroup END
#endif
#
#if executable('vls')
#  augroup LspVls
#    au!
#    au User lsp_setup call lsp#register_server({
#        \ 'name': 'vue-language-server',
#        \ 'cmd': {server_info->['vls']},
#        \ 'whitelist': ['vue'],
#        \ 'initialization_options': {
#        \         'config': {
#        \             'html': {'suggest': v:true},
#        \             'vetur': {
#        \                 'validation': {'template': v:true, 'script': v:true, 'style': v:true},
#        \                 'completion': {'tagCasing': 'initial'}
#        \             }
#        \         }
#        \     }
#        \ })
#
#    " omnifunc
#    au FileType vue setlocal omnifunc=lsp#complete
#  augroup END
#endif
#
#if executable('docker-langserver')
#  augroup LspDocker
#  au!
#  au User lsp_setup call lsp#register_server({
#      \ 'name': 'docker-langserver',
#      \ 'cmd': {server_info->[&shell, &shellcmdflag, 'docker-langserver --stdio']},
#      \ 'whitelist': ['dockerfile'],
#      \ })
#  augroup END
#endif
#
#if executable('bash-language-server')
#  augroup LspBash
#    au!
#    au User lsp_setup call lsp#register_server({
#      \ 'name': 'bash-language-server',
#      \ 'cmd': {server_info->[&shell, &shellcmdflag, 'bash-language-server start']},
#      \ 'whitelist': ['sh'],
#    \ })
#  augroup END
#endif
#
#if executable('vim-language-server')
#  augroup LspVim
#    au!
#    au User lsp_setup call lsp#register_server({
#      \ 'name': 'vim-language-server',
#      \ 'cmd': {server_info->[&shell, &shellcmdflag, 'vim-language-server --stdio']},
#      \ 'whitelist': ['vim'],
#    \ })
#  augroup END
#endif
#
#
#au FileType * nmap <silent> <Tab>[ :LspDefinition<CR>
#au FileType * nmap <silent> <Tab>h :LspHover<CR>
#au FileType * nmap <silent> <Tab>r :LspReferences<CR>
#au FileType * nmap <silent> <Tab>i :LspImplementation<CR>
#au FileType * nmap <silent> <Tab>] :split \| :LspDefinition <CR>
#au FileType * nmap <silent> <Tab>v :vsplit \| :LspDefinition <CR>
#let g:lsp_signs_error = {'text': '✗'}
#let g:lsp_signs_warning = {'text': '!!'}
#let g:lsp_signs_enabled = 1
#let g:lsp_diagnostics_echo_cursor = 1
#let g:lsp_log_file = expand('~/.cache/tmp/vim-lsp.log')
#'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_ft = ['*']
depends = ['async.vim']
hook_add = '''
let g:asyncomplete_log_file = expand('~/.cache/tmp/asyncomplete.log')
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
let g:fzf_action = {
  \ 'ctrl-s': 'split' }

nnoremap <silent><C-p> :FZFFileList<CR>
command! FZFFileList call fzf#run(fzf#wrap({
            \ 'source': 'find . -type d -name .git -prune -o ! -name .DS_Store',
            \ 'down': '40%'}))

nnoremap <C-q> :Buffers<CR>
nnoremap <C-g> :Ag<CR>
"nnoremap <silent> <C-]> :call fzf#vim#tags(expand('<cword>'))<CR>

let g:fzf_buffers_jump = 1

command! -bang -nargs=? -complete=dir Files
            \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
'''

#[[plugins]]
#repo = 'mattn/vim-lsp-settings'
#depends = ['async.vim', 'asyncomplete.vim', 'vim-lsp', 'asyncomplete-lsp.vim']

