[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    nnoremap <silent> <S-o> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_open_cmd = 'open -a Google\ Chrome'
    let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_add = '''
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]] # TOMLのシンタックスハイライト
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescriptreact', 'typescript']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['tsx', 'jsx', 'typescriptreact']

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['vue', 'typescript', 'javascript']
hook_add = '''
let g:ale_statusline_format = ['E%d', 'W%d', 'OK']

nmap <silent> <C-w>j <Plug>(ale_next_wrap)
nmap <silent> <C-w>k <Plug>(ale_previous_wrap)

let g:ale_sign_error = '>>'
let g:ale_sign_warning = '!!'

let g:ale_fixers = {
\   'javascript': ['eslint', 'prettier'],
\   'vue': ['eslint', 'prettier'],
\   'typescript': ['eslint', 'prettier']
\}
let g:ale_linters = {
\   'javascript': ['eslint', 'prettier'],
\   'vue': ['eslint', 'prettier'],
\   'typescript': ['eslint', 'prettier']
\}

" ファイル保存時に実行
let g:ale_fix_on_save = 1

" ローカルの設定ファイルを考慮する
let g:ale_javascript_prettier_use_local_config = 1
'''

[[plugins]]
repo = "lvht/phpcd.vim"
build = "composer install"
on_fmt = ["php"]
hook_source = '''
if filereadable('phpcd_autoload.php')
  let g:phpcd_autoload_path = 'phpcd_autoload.php'
endif
'''


