// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gitlab.kaonavi.jp/ae/kgm/auth"
	"gitlab.kaonavi.jp/ae/sardine/internal/cmd/api/middleware"
)

// Injectors from middleware.go:

func InitializeAuthenticateToken() *middleware.AuthenticateToken {
	authenticator := auth.NewHS256Authenticator()
	authenticateToken := middleware.NewAuthenticateToken(authenticator)
	return authenticateToken
}
